### ISSUE TITLE
Autoloader magazine wont link to cannon

### ISSUE THREAD

**Issue by Skreetu** [Dakota0001/DakTank#32]
Name pretty much explains it. I've tried to link it to the gun a few times now to no avail.

**Comment by Dakota0001** [comment]
What kind of gun are you trying to link?

To use an autoloader mag you must have the magazine, and an autoloader gun, you then link the mag to the gun, not the gun to the mag.

**Comment by Skreetu** [comment]
I'm trying to link a 50mm cannon, I'm following your most recent tutorial.

**Comment by Dakota0001** [comment]
Yes, but is the cannon an *autoloader* or just a normal cannon?

**Comment by Skreetu** [comment]
Very new to all this, changing it to an autoloader worked. I should've paid more attention, thanks for this. 
No, it wasn't, to answer your question
